name: gg_is_github
description: Provides a method isGitHubAction which returns true if the currenct directory is running as part of a GitHub action.
version: 1.0.7
repository: https://github.com/inlavigo/gg_is_github.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0